### ISSUE TITLE
Implement a Rydberg simulator

### ISSUE THREAD

**Issue by fretchen** [qiskit-community/qiskit-cold-atom#64]
In addition to the fermionic setting and the setting of long spins Rydberg atoms are a prime system of cold atoms. This is the neutral atom implementation of qubits. They are described through the Hamiltonian:

$$
\hat{H}_{ryd} = \Omega \sum_i \sigma_{x,i} + \Delta \sum_i \sigma_{z,i} + V \sum_{i\neq j} \frac{\hat{n}_i \hat{n}_j}{|i-j|^6}
$$

The occupation number is defined as $\hat{n}_i = Z_i + \frac{1}{2}$ and the spin operators are $\sigma_{x,i} = \frac{1}{2}X_i$ as well as $\sigma_{z,i} = \frac{1}{2}Z_i$. Here, the unit of information, i.e. the individual wires in the quantum circuit, are given as quantum angular momenta or spins of length $S = 1/2$. Typical applications are:

- [Messin et al.](https://www.nature.com/articles/nphys1183), which demonstrate dynamically a Rydberg blockade.
- [Bernien et al.](https://arxiv.org/abs/1707.04344), which demonstrates larger spin structures that arise dynamically.

## Expected behavior

1. Being able to apply the `RX` and the `RZ` gate as we talk about qubits. 
2. Being able to apply the gate that implements the blockade. Let's call it `CLBOCK` for the moment.
3. Being able to apply the full Hamiltonian as some $\hat{U} = e^{i\hat{H}t}$ with three free paramters.
4. Being able to run the simulation on a remote provider.
5. Being able to run the simulation locally given that this is a qubit system.

## Current behavior

1. It is possible to implement the action of `RLX` and `RLZ`
2. Not implemented and no implementation from other `qiskit` packages is known.
3. Not implemented, but an implementation similiar to the `FHubbard` could be expected.
4. Not possible as there is no way to send out `CBLOCK` or `ufull` strings yet, which a backend could implement.
5. Very unclear how this would work out to me personally.

## Proposed solution

- Implement the necessary gates provider to make it possible to send out the necessary strings.
- For each gate this would imply the creation of the class:

```
from qiskit.circuit import Gate

class RX(Gate):
    """
    Need to implement.
    """

class RZ(Gate):
    """
    Need to implement.
    """

class CBlock(Gate):  # Better name?
    """    
    Need to implement.
    """
    
class UFull(Gate):  # Better name?
    """
    Need to implement.
    """
```

- For all four gates it would seem reasonable to follow a similiar implementation as for the fermions. In a first step it feels important to be able to run the system remotely.  
- Changes in the `providers` folder seem minimal. Is it necessary to create an additional `RemoteQubitBackend` ?
- Should `rydberg` be a full folder like `spins` and `fermions` ? It seems strange to reimplement everything here. A minimal extension of the `spin_gate_library` feels more natural.
- Otherwise it feels that a `rydberg` provider has to implement at least a `base_rydberg_backend` and a `rydberg_gate_library`. However, I cannot see the benefit it redoing all the logic of the local simulation for $S=1/2$. Why would we have most of the code of `..._circuit_solver` and `..._simulator_backend` twice ?

**Comment by eggerdj** [comment]
Here are some comments and proposed action

1. If we interpret Rydberg as spin but in the limiting case of spin 1/2 then I don't think we need another base backend.
2. Based on 1. we do not need to re-implement the X and Y rotations. Also we could use the `rx` and `ry` implemented in Qiskit Terra.
3. For `CBlock` and `UFull` I suggest `RydbergBlock` and `RydbergFull`. Slightly longer but more expressive.

I suggest the following course of action:

a. Implement `RydbergBlock` and `RydbergFull` in the spin gate library here: https://github.com/Qiskit-Extensions/qiskit-cold-atom/blob/main/qiskit_cold_atom/spins/spins_gate_library.py

b. Make sure that `RydbergBlock` and `RydbergFull` work with the Spin backends without having us re-implement the providers, backends, etc.

c. Make sure that `RydbergBlock` and `RydbergFull` and work with a standard Qiskit Aer qubit-based solver. This should be possible if `RydbergBlock` and `RydbergFull` define their qubit matrices which they should.

d. Make sure these gates are properly communicated over the API. I think this should come for free.

**Comment by LaurinFischer** [comment]
Thanks a lot or summarizing your thoughts on this. I agree with Daniel that it would be best to base as much as we can on the existing modules to support spin circuits, and duplicate as little as possible. 

- to point 5: If all the gates are defined in the qiskit cold atom style (with a generating Hamiltonian described by a `SpinOp`), then the existing `SpinSimulator` should be able to run the simulations with no further modifications needed. As Daniel says, a natural place for these gates would be to simply add them as a `SpinGate` (rather than the qiskit `Gate` you suggested above) in the `spins_gate_library`. 
If you wanna run the same simulations on a standard qiskit qubit simulator (Aer) this should also be fine, as this will query the native `to_matrix()` method. 
It would be pretty cool to see the same circuit object can be simulated with both qiskit_cold_atom and qiskit_aer simulators. 
- If we want a mock backend that acts as a dedicated Rydberg simulator in qiskit_cold_atom, I'd suggest to create something similar to the `CollectiveSpinSimulator`, e.g. `RydbergSimulator` as a subclass of the `SpinSimulator`. This will then define a more restricted connectivity, the basis gate set, set the spin length to 1/2, etc. Besides this, I don't think we any additional rydberg-specific backends. 
- To point 1: To ensure simulation is possible within Qiskit cold atom, we should use the existing `RLXGate` and `RLYGate`. The difference to the qiskit `rx` an `ry` gates is that the former define the generators which the `SpinSimulator` relies on.
- To point 4: I agree with Daniel here that this should not require any changes on the qiskit_cold_atom side. The `RemoteSpinBackend` should be sufficiently generic that it simply prepares the json payloads in the circuit in a standardized way, which the remote backend then needs to parse. 

For these reasons, I agree that no full `rydberg` folder will be required. I also agree on the course of action Daniel laid out, with the addition of creating a `RydbergSimulator` mock backend to make the description of this hardware more concrete.
